Database:
   address: 127.0.0.1
   port: 3306
   dbname: forgestormdb
   username: root
   password: ""
Features:
   PlayerCompassMenu: true
   PlayerScoreboardTeams: true
   PlayerNewChecker: true
   PlayerOperator: true
   PlayerBanKicker: true
   ServerSpawn: true
   SimpleChat: true
   UsergroupChat: false
   LobbyPlayer: true
   PlayerGreeting: true
   PlayerListText: true
   PlayerBossBar: true
   CitizenManager: true
   WorldSettings: true
   NewChestLoot: false
   ChestLoot: false
   DragonEggLoot: false
   HiddenPaths: true
   MobManager: false
   DoubleJump: true
   Lantern: false
   WorldHologram: true
   EzImgMessage: true