Database:
  address: 127.0.0.1
  port: 3306
  dbname: forgestormdb
  username: root
  password: ""
Games:
#- INFECTION
#- MOB_MURDER
#- OITC
- PIRATE_ATTACK
- SHEER_SHEEP
#- MOW_GRASS
Features:
  JazzyJukebox: true
  MinigameFramework: true
  PlayMidi: true
  DeletePlayerWorldData: false
  PersistentInventory: false
  FishingSkill: true
  WoodCutting: true
  Farming: true
  Mining: true
  ItemDatabase: true
  GameWorldManager: false #false when minigames enabled
  ArmorManager: true
  BasicBuildProtection: true
  Roll: true
  HelpBookTest: true
  AnvilTest: true
  RealmManager: false
  GameTipAnnouncer: false #false when minigames enabled
  PlayerCompassMenu: true
  PlayerNewChecker: false #false when minigames enabled
  PlayerOperator: true
  PlayerBanKicker: true
  ServerSpawn: true
  SimpleChat: true
  UsergroupChat: false
  LobbyPlayer: true
  PlayerGreeting: false #false when minigames enabled
  PlayerListText: true
  PlayerBossBar: false #false when minigames enabled
  CitizenManager: true
  WorldSettings: false #false when minigames enabled
  ChestLoot: true
  DragonEggLoot: true
  HiddenPaths: true
  MobManager: true
  DoubleJump: true
  NewLantern: true
  WorldHologram: true
  EzImgMessage: true