Database:
   address: 127.0.0.1
   port: 3306
   dbname: forgestormdb
   username: root
   password: ""
Features:
   BasicBuildProtection: true
   Roll: true
   HelpBookTest: true
   AnvilTest: true
   RealmManager: true
   GameTipAnnouncer: true
   PlayerCompassMenu: true
   ScoreboardTeams: true
   PlayerNewChecker: true
   PlayerOperator: true
   PlayerBanKicker: true
   ServerSpawn: true
   SimpleChat: true
   UsergroupChat: false
   LobbyPlayer: true
   PlayerGreeting: true
   PlayerListText: true
   PlayerBossBar: true
   CitizenManager: true
   WorldSettings: true
   ChestLoot: true
   DragonEggLoot: false
   HiddenPaths: true
   MobManager: true
   DoubleJump: true
   Lantern: false
   WorldHologram: true
   EzImgMessage: true