name: ForgeStorm-SpigotCore
main: com.forgestorm.spigotcore.SpigotCore
version: 1.0.0
description: ForgeStorm SpigotCore
author: Andrew Brown & Joseph Rugh
website: http://www.forgestorm.com/
load: POSTWORLD
depend: [ProtocolLib, LibsDisguises, TitleManager, Citizens, ItemNBTAPI, NoteBlockAPI]
