name: FS-SpigotCore
main: com.forgestorm.spigotcore.SpigotCore
version: 0.1.0
description: ForgeStorm SpigotCore
author: Andrew Brown & Joseph Rugh
website: http://www.forgestorm.com/
load: POSTWORLD
depend: [TitleManager, Citizens]
commands:
   feature:
   cmsg:
   spawn:
   chaticon: